application: ptchatbot
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tasks/.*
  script: bot.app
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: bot.app

inbound_services:
- xmpp_subscribe
- xmpp_error
#- xmpp_message
#

libraries:
- name: jinja2
  version: latest

